### ISSUE TITLE
HuFlex for HuC6260 issue

### ISSUE THREAD

**Issue by TruREALigion** [zaxour/TurboNanza#10]
Hello

Are pins 41 (+5V) and 42 (Y+) connected or did I accidentally bridge them?

![IMG_8901](https://github.com/zaxour/TurboNanza/assets/78335185/3183a32c-2eea-4b2c-bd75-73c91f38d95e)

**Comment by zaxour** [comment]
Hi,

They are connected together by design, as Y+ actually refers to the voltage
supply for the luma section (likely some kind of output buffer/driver).
False alarm!

**Comment by TruREALigion** [comment]
Excellent - I thought I was losing my mind scraping my iron over and over!
