### ISSUE TITLE
New TurboNanza install black screen and buzzing sound

### ISSUE THREAD

**Issue by TruREALigion** [zaxour/TurboNanza#9]
I installed on PC Engine but no picture and loud buzzing sound.  Wondering what troubleshooting steps I can try?  

It works fine when I plug into my IFU unit.

I used SCART RetroGamingCablesUK and HD retrovision Component cable with Saturn converter 

![IMG_8866](https://github.com/zaxour/TurboNanza/assets/78335185/31ddbb09-2237-471f-a9a0-3ee0613bb182)
![IMG_8881](https://github.com/zaxour/TurboNanza/assets/78335185/c58cc2db-ccd5-4f41-ad71-f0024b4311c0)
![IMG_8882](https://github.com/zaxour/TurboNanza/assets/78335185/ae288e40-eccd-4371-b45c-9f77c0178ba6)
![IMG_8883](https://github.com/zaxour/TurboNanza/assets/78335185/53907100-fbff-4121-8969-cb798e5e8b04)
![IMG_8880](https://github.com/zaxour/TurboNanza/assets/78335185/adb47707-960b-4f90-b561-a3b687a97b6a)

**Comment by zaxour** [comment]
Hi,

Can you show me how you installed the DIN? I've seen people install it
upside down, just want to make sure that's not the case.

Thanks!

**Comment by TruREALigion** [comment]
I didn’t install the DIN actually.  It is just hanging outside.  Does it need to be mounted in for it to work?

**Comment by zaxour** [comment]
It doesn’t need to be mounted to the system to work. However, I would like to confirm how you’ve soldered on the small DIN board.

**Comment by TruREALigion** [comment]
See attached

![image](https://github.com/zaxour/TurboNanza/assets/78335185/3eed142c-f261-4665-aab5-56f5c4c4c819)

![IMG_8880](https://github.com/zaxour/TurboNanza/assets/78335185/aaeaed72-0334-46a2-94b4-89cfac008b16)

**Comment by zaxour** [comment]
The din board is upside down, that would be why you’re not getting an output. Please desolder and flip it over.

**Comment by TruREALigion** [comment]
That explains everything!

Will update back and close if resolved.

**Comment by TruREALigion** [comment]
Fixed.  I had the DIN upside-down.
